run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Exclude linting for test files
    - path: _test\.go
      linters:
        - errcheck
