name: Semantic Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (defaults shown)
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure which scopes are allowed (empty = all scopes allowed)
          scopes: |
          # Configure that a scope must always be provided
          requireScope: false
          # For work-in-progress PRs you can typically use draft pull requests
          # from GitHub. However, private repositories on the free plan don't have
          # this feature and therefore this action allows you to opt-in to using the
          # special "[WIP]" prefix to indicate this state.
          wip: true
          # When using "Squash and merge" on a PR with only one commit, GitHub
          # will suggest using that commit message instead of the PR title for the
          # merge commit. This option validates the commit message as well.
          validateSingleCommit: true

  semantic-branch-name:
    name: Check Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: "^(main|master|develop|dev)$|^(feature|feat|fix|bugfix|hotfix|release|docs|style|refactor|perf|test|build|ci|chore|revert)/.+$"
          allowed_prefixes: "feature,feat,fix,bugfix,hotfix,release,docs,style,refactor,perf,test,build,ci,chore,revert"
          ignore: main,master,develop,dev
          min_length: 3
          max_length: 100

  semantic-commits:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
